export const LOG_IN_ATTEMPT = 'LOG_IN_ATTEMPT';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_UP_ATTEMPT = 'SIGN_UP_ATTEMPT';
export const RESET_REGISTER_FAIL = 'RESET_REGISTER_FAIL';
export const ADD_USER_ASSET = 'ADD_USER_ASSET';
